### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by Easy-Cloud-in** [thealoneprogrammer/query-string-hash#2]
**npm install query-string-hash** 
throws this error:

npm WARN @ec-website-restapi/api@1.0.0 No description
npm WARN @ec-website-restapi/api@1.0.0 No repository field.
npm WARN @ec-website-restapi/api@1.0.0 No license field.

**Comment by thealoneprogrammer** [comment]
Hi, it's just a warning that can be ignored.
